Skeleton for balances component(currently wallet address hard coded)
edenworky/Coindash pull request #1
Opened 2016-10-05 04:16 UTC by negedzuregal

2016-10-05 15:37 UTC, edenworky requested changes

2016-10-05 15:37 UTC, edenworky commented on app/components/BalanceCell/index.js
> +class BalanceCell extends React.Component { // eslint-disable-line react/prefer-stateless-function
The ES2015 class syntax is unpreferable. Use the `create-class` syntax instead. You can check the `internals/generators/component/create-class.js.hbs` generator file, it's a very simple change to do by hand.

2016-10-05 15:37 UTC, edenworky commented on app/components/BalanceCell/tests/index.test.js
> +    expect(true).toEqual(false);
This is a failing test. Skip or implement. You can skip by adding `it.skip('Expe...`.

2016-10-05 15:37 UTC, edenworky commented on app/components/AddTokenForm/index.js
> +* AddTokenForm
This is a component, not just a function. It doesn't add a token form, it *is* a token form. Please rename appropriately.

2016-10-05 15:37 UTC, edenworky commented on app/components/AddTokenForm/index.js
> +        onSubmit={this.onFormSubmit.bind(this)}
Is `bind(this)` necessary here?

2016-10-05 15:37 UTC, edenworky commented on app/components/AddTokenForm/index.js
> +    	console.log("error:");
You're only printing the error here without actually doing anything with it. The default is smarter.

2016-10-05 15:37 UTC, edenworky commented on app/components/AddTokenForm/index.js
> +    onFormError(errors) {
There's only one error

2016-10-05 15:37 UTC, edenworky commented on app/components/AddTokenForm/index.js
> +  title: "Fill token details",
All these strings should be abstracted to the `messages` file.

2016-10-05 15:37 UTC, edenworky commented on app/components/AddTokenForm/tests/index.test.js
> +    expect(true).toEqual(false);
Same as below

2016-10-05 15:37 UTC, edenworky commented on app/containers/BalanceContainer/index.js
> +import $ from 'jquery';
See `package.json`

2016-10-05 15:37 UTC, edenworky commented on app/components/BalanceCell/index.js
> +class BalanceCell extends React.Component { // eslint-disable-line react/prefer-stateless-function
This is true for all the classes you've created, please change them appropriately.

2016-10-05 15:37 UTC, edenworky commented on app/containers/BalanceContainer/index.js
> +import BigNumber from 'bignumber.js';
Why is `bignumber.js` necessary? What can you do with it that you can't do with plain JS?

2016-10-05 15:37 UTC, edenworky commented on app/containers/BalanceContainer/index.js
> +    if (this.props.token == null) {
`==` is a less specific equality operator. Default to `===`.
`null` is a falsey value. A cleaner way to write this in JS would be `if (!this.props.token) {...}`.

2016-10-05 15:37 UTC, edenworky commented on app/containers/BalanceContainer/index.js
> +    var data = $.param(this.props.token.balanceCallData());
`var` is deprecated for most uses. Use `let` and `const` instead.

2016-10-05 15:37 UTC, edenworky commented on app/containers/BalanceContainer/index.js
> +    $.ajax({
`ajax` is not necessary here. Use the [Fetch API](https://davidwalsh.name/fetch).

2016-10-05 15:37 UTC, edenworky commented on app/containers/BalancesContainer/Token.js
> +	    this.contractAddress = contractAddress;
Spacing issue

2016-10-05 15:37 UTC, edenworky commented on app/containers/BalancesContainer/Token.js
> +		if (unitValue === undefined) {
`undefined` is also a falsey value. `if (!unitValue) {...}`

2016-10-05 15:37 UTC, edenworky commented on app/containers/BalancesContainer/Token.js
> +	    for(var i=0;i<arrVals.length;i++) val+=this.padLeft(arrVals[i],64);
A more JS-y way to write this is with a [`for...in` loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in)

2016-10-05 15:37 UTC, edenworky commented on app/containers/BalancesContainer/index.js
> +import W from '../../utils/Wallet/Wallet'
Not readable, please change to `Wallet`

2016-10-05 15:37 UTC, edenworky commented on app/containers/BalancesContainer/index.js
> +            <AddTokenForm onSubmited={this.onSubmitedToken.bind(this)} />
Typo

2016-10-05 15:37 UTC, edenworky commented on app/containers/Dashboard/index.js
> +      <div >
Don't remove the `className`, that's the CSS binding

2016-10-05 15:37 UTC, edenworky commented on app/utils/Wallet/Token.js
> +import BigNumber from 'bignumber.js';
Is this a duplicate of the file from before? Why?

2016-10-05 15:37 UTC, edenworky commented on app/utils/Wallet/Wallet.js
> +import { Token } from './Token'
Name index files `index.js`. This way you can just import `from 'utils/Wallet'` instead of `from 'utils/Wallet/Wallet'`

2016-10-05 15:37 UTC, edenworky commented on app/utils/Wallet/Wallet.js
> +	    for (var i = 0; i < allTokens.length; i++) {
Again, `for...in`

2016-10-05 15:37 UTC, edenworky commented on app/utils/Wallet/Wallet.js
> +    	  console.log("token symbol: " + symbol + ", address: " + address + ", decimal: " + decimal);
Check out [template strings](https://developers.google.com/web/updates/2015/01/ES6-Template-Strings) 😉

2016-10-05 15:37 UTC, edenworky commented on app/utils/Wallet/Wallet.js
> +const W = Wallet.walletFromDisk();
`walletFromDisk` doesn't make sense. Are you trying to instantiate `Wallet`?

2016-10-05 15:37 UTC, edenworky commented on app/utils/Wallet/Wallet.js
> +Object.freeze(W);
`Object.freeze` is an intensive operation and should only be used for debugging purposes

2016-10-05 15:37 UTC, edenworky commented on package.json
>    "dependencies": {
Everything under `dependencies` gets shipped with the app to the user, and takes time and space. We should keep this list minimal. We have no use for `jquery`, please remove it. I asked above about `bignumber.js`. The other 2 are great.

2016-10-05 15:41 UTC, alonmuroch commented on app/utils/Wallet/Wallet.js
> +const W = Wallet.walletFromDisk();
yes because we will probably instantiate the wallet from local disk or something.

2016-10-05 15:43 UTC, negedzuregal commented on app/components/BalanceCell/index.js
> +class BalanceCell extends React.Component { // eslint-disable-line react/prefer-stateless-function
This is also true to the classes you've created. See dashboard for example.

2016-10-05 15:44 UTC, negedzuregal commented on app/components/BalanceCell/tests/index.test.js
> +    expect(true).toEqual(false);
fixed

2016-10-05 15:47 UTC, negedzuregal commented on app/components/AddTokenForm/index.js
> +* AddTokenForm
fixed

2016-10-05 15:49 UTC, negedzuregal commented on app/components/AddTokenForm/index.js
> +        onSubmit={this.onFormSubmit.bind(this)}
yes ES6 disconnects context automatically

2016-10-05 15:49 UTC, negedzuregal commented on app/components/AddTokenForm/index.js
> +    	console.log("error:");
we should add it to a TODO or something

2016-10-05 15:49 UTC, negedzuregal commented on app/components/AddTokenForm/tests/index.test.js
> +    expect(true).toEqual(false);
fixed

2016-10-05 15:49 UTC, alonmuroch commented on app/containers/BalanceContainer/index.js
> +import $ from 'jquery';
see what?

2016-10-05 15:50 UTC, negedzuregal commented on app/containers/BalanceContainer/index.js
> +import BigNumber from 'bignumber.js';
Copied from MyEtherWallet, thats how they do it. 
BigNumber is a class used throughout all bitcoin related projects to handle balances

2016-10-05 15:51 UTC, negedzuregal commented on app/containers/BalanceContainer/index.js
> +    if (this.props.token == null) {
fixed

2016-10-05 15:52 UTC, negedzuregal commented on app/containers/BalanceContainer/index.js
> +    var data = $.param(this.props.token.balanceCallData());
fixed

2016-10-05 15:52 UTC, negedzuregal commented on app/containers/BalanceContainer/index.js
> +    $.ajax({
currently it was copied from MyEtherWallet project for speed

2016-10-05 15:53 UTC, negedzuregal commented on app/containers/BalancesContainer/Token.js
> +	    this.contractAddress = contractAddress;
fixed

2016-10-05 15:54 UTC, negedzuregal commented on app/containers/BalancesContainer/index.js
> +import W from '../../utils/Wallet/Wallet'
Wallet is the class name, how will you call a global singleton of it?

2016-10-05 15:54 UTC, negedzuregal commented on app/containers/Dashboard/index.js
> +      <div >
fixed

2016-10-05 15:55 UTC, alonmuroch commented on app/utils/Wallet/Wallet.js
> +Object.freeze(W);
removed

2016-10-13 11:09 UTC, edenworky commented on app/components/BalanceCell/index.js
> +class BalanceCell extends React.Component { // eslint-disable-line react/prefer-stateless-function
Oh whoops. Fixed.

2016-10-13 11:13 UTC, edenworky commented on app/components/AddTokenForm/index.js
> +    	console.log("error:");
React's default error handling is better. Don't catch the error; if we'll need custom logic we can implement later.

2016-10-13 11:17 UTC, edenworky commented on app/containers/BalancesContainer/index.js
> +import W from '../../utils/Wallet/Wallet'
It's not global, it's for this file specifically. Regardless, `Wallet` is the most explicit name. Don't you agree?

2016-10-13 11:20 UTC, edenworky approved these changes

2016-10-17 20:46 UTC, edenworky requested changes

2016-10-17 20:46 UTC, edenworky commented on app/containers/BalanceContainer/index.js
> +    let data2 = $.param(this.props.token.balanceCallData());
What is `$`?

2016-10-17 20:46 UTC, edenworky commented on app/utils/AjaxUtils.js
> +	  var array = [];
Do not use `var` ever. Also in line 5.

2016-10-17 20:46 UTC, edenworky commented on app/containers/BalanceContainer/index.js
>  export class BalanceContainer extends React.Component { // eslint-disable-line react/prefer-stateless-function
ES2015 class syntax is unpreferable. Use `React.createClass` by default.

2016-10-17 20:46 UTC, edenworky commented on app/containers/BalanceContainer/index.js
> -import $ from 'jquery';
Remove also from `package.json`.

2016-10-18 04:21 UTC, negedzuregal commented on package.json
>    "dependencies": {
removed

2016-10-18 04:21 UTC, negedzuregal commented on app/utils/AjaxUtils.js
> +	  var array = [];
fixed

2016-10-18 04:21 UTC, negedzuregal commented on app/containers/BalanceContainer/index.js
> +    let data2 = $.param(this.props.token.balanceCallData());
fixed

2016-10-19 16:56 UTC, edenworky requested changes

2016-10-19 16:56 UTC, edenworky commented on package.json
> +    "jquery": "^3.1.1",
Awesome work, just remove this and I'll merge. 😃

2016-10-22 10:35 UTC, merged